name: skeleton_animation
description: Display skeleton animations in your app. It works on android, iOS and the web.
version: 0.1.4
repository: https://github.com/wjtje/flutter-skeleton-animation

environment:
  sdk: ">=2.12.0 <3.0.0"
#  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
